# Run with bin/reqtest

HEAD https://remino.net/dresscss
HTTP/2 301
Location: /dress.css/

HEAD https://remino.net/dresscss/dress.css
HTTP/2 301
Location: /dress.css/dress.css

HEAD https://remino.net/semcss
HTTP/2 301
Location: /dress.css/

HEAD https://remino.net/semcss/dress.css
HTTP/2 301
Location: /dress.css/dress.css

HEAD https://remino.net/sem.css
HTTP/2 301
Location: /dress.css/

HEAD https://remino.net/sem.css/dress.css
HTTP/2 301
Location: /dress.css/dress.css
