
location = /dresscss {
	return 301 /dress.css/;
}

location /dresscss/ {
	rewrite ^/dresscss/(.*) /dress.css/$1 permanent;
}

location = /semcss {
	return 301 /dress.css/;
}

location /semcss/ {
	rewrite ^/semcss/(.*) /dress.css/$1 permanent;
}

location = /sem.css {
	return 301 /dress.css/;
}

location /sem.css/ {
	rewrite ^/sem\.css/(.*) /dress.css/$1 permanent;
}


